spec: flatprofiles
spec_version: "1.1.1"

data:
  model_profiles:
    default:
      #provider: deepinfra
      #name: deepinfra/MiniMaxAI/MiniMax-M2.5
      #name: openrouter/arcee-ai/trinity-large-preview:free
      name: openrouter/openai/gpt-5-mini
      #temperature: 0.2
      #max_tokens: 8000

    subcall:
      #provider: deepinfra
      #name: deepinfra/MiniMaxAI/MiniMax-M2.5
      #name: openrouter/arcee-ai/trinity-large-preview:free
      name: openrouter/openai/gpt-5-mini
      #temperature: 0.2
      #max_tokens: 8000

  default: default

metadata:
  description: "Model profiles for RLM v2 example"
  tags: ["rlm", "recursive", "repl"]
